#!/bin/sh
echo "Running dotnet format..."
cd "$(pwd)"
echo "$(pwd)"
read -p "Press enter to continue"
dotnet format \ChoreBuddies.Frontend.sln --include . --verbosity quiet
git add . # Add the formatted files back to the commit