# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Install dotnet-format tool
      run: dotnet tool install -g dotnet-format
      
    - name: Check code formatting
      run: |
        # This command will fail (exit code 1) if any files are not formatted correctly.
        dotnet format ChoreBuddies.Frontend/ChoreBuddies.Frontend.csproj --verify-no-changes --verbosity detailed
